
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace MyTodoList {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyTodoList : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.Window listOfTaskView;
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.CheckBox checkBox;
        
        private Terminal.Gui.CheckBox checkBox2;
        
        private void InitializeComponent() {
            this.checkBox2 = new Terminal.Gui.CheckBox();
            this.checkBox = new Terminal.Gui.CheckBox();
            this.label = new Terminal.Gui.Label();
            this.listOfTaskView = new Terminal.Gui.Window();
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.ColorScheme = this.greenOnBlack;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.Title = "Task Management System by Raldin Casidar";
            this.listOfTaskView.Width = Dim.Percent(50f);
            this.listOfTaskView.Height = Dim.Percent(100f);
            this.listOfTaskView.X = 0;
            this.listOfTaskView.Y = 0;
            this.listOfTaskView.Visible = true;
            this.listOfTaskView.ColorScheme = this.greenOnBlack;
            this.listOfTaskView.Modal = false;
            this.listOfTaskView.IsMdiContainer = false;
            this.listOfTaskView.Data = "listOfTaskView";
            this.listOfTaskView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.listOfTaskView.Border.Effect3D = false;
            this.listOfTaskView.Border.Effect3DBrush = null;
            this.listOfTaskView.Border.DrawMarginFrame = true;
            this.listOfTaskView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.listOfTaskView.Title = "";
            this.Add(this.listOfTaskView);
            this.label.Width = 61;
            this.label.Height = 1;
            this.label.X = 0;
            this.label.Y = 0;
            this.label.Visible = true;
            this.label.Data = "label";
            this.label.Text = "Tasks";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.listOfTaskView.Add(this.label);
            this.checkBox.Width = 6;
            this.checkBox.Height = 1;
            this.checkBox.X = 0;
            this.checkBox.Y = Pos.Bottom(label) + 4;
            this.checkBox.Visible = true;
            this.checkBox.Data = "checkBox";
            this.checkBox.Text = "Kumain ng Almusal";
            this.checkBox.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.checkBox.Checked = false;
            this.listOfTaskView.Add(this.checkBox);
            this.checkBox2.Width = 6;
            this.checkBox2.Height = 1;
            this.checkBox2.X = 0;
            this.checkBox2.Y = Pos.Bottom(checkBox) + 1;
            this.checkBox2.Visible = true;
            this.checkBox2.Data = "checkBox2";
            this.checkBox2.Text = "Kumain ng Almusal";
            this.checkBox2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.checkBox2.Checked = false;
            this.listOfTaskView.Add(this.checkBox2);
        }
    }
}
